return T{
	['Mythic'] = S{
		'Nyzul Tokens',
		'Therion Ichor' 
	},
	['Crafting'] = S{ 
		'Crafter Points',                            
        'Fire Crystals',                         
        'Ice Crystals',                          
        'Wind Crystals',                         
        'Earth Crystals',                        
        'Lightning Crystals',                    
        'Water Crystals',                        
        'Light Crystals',                  
        'Dark Crystals',
	},
	['Spheres'] = S{
        'Liquefaction Spheres Set',
        'Induration Spheres Set',                    
        'Detonation Spheres Set',                    
        'Scission Spheres Set',                      
        'Impaction Spheres Set',                     
        'Reverberation Spheres Set',                 
        'Transfixion Spheres Set',                   
        'Compression Spheres Set',                   
        'Fusion Spheres Set',                        
        'Distortion Spheres Set',                    
        'Fragmentation Spheres Set',                 
        'Gravitation Spheres Set',
        'Light Spheres Set',
        'Darkness Spheres Set',                           
        'Fire Crystals Set',                         
        'Ice Crystals Set',                          
        'Wind Crystals Set',                         
        'Earth Crystals Set',                        
        'Lightning Crystals Set',                    
        'Water Crystals Set',                        
        'Light Crystals Set',                  
        'Dark Crystals Set',
	},
	['Rems'] = S{
        "Rems Tale Chapter 1",                   
        "Rems Tale Chapter 2",                   
        "Rems Tale Chapter 3",                   
        "Rems Tale Chapter 4",                   
        "Rems Tale Chapter 5",                   
        "Rems Tale Chapter 6",                   
        "Rems Tale Chapter 7",                   
        "Rems Tale Chapter 8",                   
        "Rems Tale Chapter 9",                   
        "Rems Tale Chapter 10",    
	},
}